sudo: required

sudo: true

language: python
python:
  - "3.4"
  - "3.5"
  # PyPy versions


# command to install dependencies
install:
  - pip install pandas
  - pip install numpy
  - pip install folium
  - pip install geopy
  - pip install matplotlib
  - pip install python3-tk

script: main.py