sudo: required

sudo: true

language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  # PyPy versions
  #- "pypy"  # PyPy2 2.5.0

# command to install dependencies
install:
  - pip install pandas
  - pip install numpy
  - pip install folium
  - pip install geopy